'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const activityList=[['🍜','吃饭'],['🎬','看电影'],['🚶','散步'],['🖼️','逛展'],['🛍️','逛街'],['🎮','打游戏'],['🎲','桌游'],['🎤','唱歌'],['☕','咖啡 / 下午茶'],['🤲','你来定'],['✏️','自定义']];
const mealList=[['🍲','火锅'],['🍢','烧烤'],['🍣','日料'],['🥩','烤肉'],['🥟','粤菜'],['🍝','西餐'],['🥨','小吃'],['🤲','随便'],['✏️','自定义']];
const teaList=[['☕','咖啡'],['🧋','奶茶'],['🍰','甜品'],['🤲','你来定'],['✏️','自定义']];
const initial=()=>({date:'',time:'',dateFree:false,timeFree:false,sleepIn:false,prefs:[],activities:[],customActivity:'',meal:'',customMeal:'',tea:'',customTea:'',place:'',placeFree:false});
let state=initial(),step=0,noCount=0;
let cardTheme='cinema', touchCount=0, lastActivity='';
const images={hope:'assets/hope.webp',sad:'assets/sad.webp',happy:'assets/happy.webp',lying:'assets/lying.webp',belly:'assets/belly.webp',rolling:'assets/rolling.webp',wave:'assets/wave.webp',laugh:'assets/laugh.webp',peace:'assets/peace.webp',plead:'assets/plead.webp',bashful:'assets/user-reactions.png',pout:'assets/user-reactions.png',eager:'assets/user-reactions.png',grin:'assets/user-reactions.png'};
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const needsFood=()=>state.activities.includes('吃饭')||state.activities.includes('咖啡 / 下午茶');
const route=()=>[0,1,2,...(needsFood()?[3]:[]),4,5];
function go(n){step=n;render();window.scrollTo({top:0,behavior:'smooth'});$('#app h1')?.focus({preventScroll:true});}
function back(){const r=route();go(r[Math.max(0,r.indexOf(step)-1)]);}
function showToast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>$('#toast').style.display='none',3200);}
const moodLabels={hope:'期待中',sad:'陷入沉思',happy:'偷偷开心',lying:'躺平等你',belly:'馋了馋了',rolling:'原地打滚',wave:'嗨！是我',laugh:'笑不活了',peace:'耶！约上了',plead:'撒个娇嘛',bashful:'委屈巴巴',pout:'真的不来嘛',eager:'已经等不及了',grin:'嘴角压不住了'};
const referenceCrops={grin:{x:22,y:7,w:220,h:220},bashful:{x:22,y:315,w:220,h:222},eager:{x:22,y:547,w:220,h:215},pout:{x:22,y:791,w:220,h:184}};
function referenceStyle(mood){const r=referenceCrops[mood],W=r.W||250,H=r.H||988;return `background-image:url('${images[mood]}');background-size:${W/r.w*100}% ${H/r.h*100}%;background-position:${r.x/(W-r.w)*100}% ${r.y/(H-r.h)*100}%;aspect-ratio:${r.w}/${r.h}`;}
function moodArt(mood,id=''){const identity=id?` id="${id}"`:'';return referenceCrops[mood]?`<span${identity} class="mood-art reference-art" role="img" aria-label="${moodLabels[mood]}的奶娃" style="${referenceStyle(mood)}"></span>`:`<img${identity} class="mood-art" src="${images[mood]}" alt="${moodLabels[mood]}的奶娃">`;}
function head(title,subtitle,mood='hope'){return `<button class="back" data-back>← 返回修改</button><div class="step-head"><div><span class="step-num">DATE REQUEST / 0${step}</span><h1 tabindex="-1">${title}</h1><p aria-live="polite">${subtitle}</p></div><figure class="reaction" data-mood="${mood}">${moodArt(mood)}<figcaption>${moodLabels[mood]}</figcaption></figure></div>`;}
function chips(items,selected,group){return `<div class="chips">${items.map(t=>`<button class="chip" data-group="${group}" data-value="${esc(t)}" aria-pressed="${selected.includes(t)}">${esc(t)}</button>`).join('')}</div>`;}
function options(items,selected,group){return `<div class="grid">${items.map(([e,t])=>`<button class="option" data-group="${group}" data-value="${esc(t)}" aria-pressed="${selected.includes(t)}"><span class="emoji" aria-hidden="true">${e}</span>${esc(t)}</button>`).join('')}</div>`;}
function next(label='就这么定，下一步 →'){return `<p class="error" id="error" role="alert"></p><div class="bottom-action"><button class="primary" id="next">${label}</button></div>`;}
function render(){if(typeof composerMode!=="undefined"&&composerMode){renderComposer();return;}const r=route();$('#progress').innerHTML=r.map((_,i)=>`<span class="${i<=r.indexOf(step)?'done':''}"></span>`).join('');$('#counter').textContent=step===0?'NO. 001':`${String(r.indexOf(step)+1).padStart(2,'0')} / ${String(r.length).padStart(2,'0')}`;let html='';
if(step===0){html=`<div class="intro"><div><p class="eyebrow">SPECIAL INVITATION ↗</p><h1 tabindex="-1">出来一下，<br>我想<span class="highlight">见你。</span></h1><p class="sub">没有什么大事。<br>就是想把想你，改成见你。</p></div><div class="meme-frame">${moodArt("grin","heroMeme")}</div></div><div class="bubble" id="plead" aria-live="polite">奶娃：嘴替已上线，这个约会你就赴吧。</div><div class="dodge-zone"><button class="primary" id="yes">行，给你个机会 ↗</button><div class="dodge-track"><button class="secondary no" id="no">不去 🙃</button></div></div><p class="tiny intro-note">选个时间，挑点想做的事。剩下的，见面说。</p>`;}
if(step===1){html=head('哪天可以见到你？',state.sleepIn?'你睡到自然醒，我躺平等你。醒了吱一声。':state.timeFree?'你把时间交给我，我把期待拉满。':'你答应了！奶娃已经开始搓手等出门。',state.sleepIn?'lying':state.timeFree?'happy':'eager')+`<div class="fields"><label class="field">见面日期<input id="date" type="date" min="${today()}" value="${esc(state.date)}" ${state.dateFree?'disabled':''}></label><label class="field">见面时间<input id="time" type="time" value="${esc(state.time)}" ${state.timeFree||state.sleepIn?'disabled':''}></label></div>`+chips(['日期你来定','时间你来定','睡到自然醒'],[...(state.dateFree?['日期你来定']:[]),...(state.timeFree?['时间你来定']:[]),...(state.sleepIn?['睡到自然醒']:[])],'free')+`<p class="section-label">再给一点小暗示<span>可多选 · 作为补充偏好</span></p>`+chips(['午后','傍晚','晚饭后','夜一点也行','你来定'],state.prefs,'prefs')+next('时间暗示给你了 →');}
if(step===2){html=head(esc(invitation.to)+'想要做什么',activityReaction().text,activityReaction().mood)+options(activityList,state.activities,'activities')+(state.activities.includes('自定义')?`<label class="field">还有什么想一起做？<input id="customActivity" maxlength="60" placeholder="比如：去江边吹风" value="${esc(state.customActivity)}"></label>`:'')+next(esc(invitation.to)+'想要 '+esc(invitation.to)+'得到');}
if(step===3){html=head('先抓住谁的胃？',state.meal==='随便'||state.tea==='你来定'?'收到，随便是世界上最难找的一家店。':state.meal||state.tea?'已经开始馋了。说的是饭，也可能是约会。':'肚子已经就位，就差你来对面坐。',state.meal==='随便'||state.tea==='你来定'?'sad':'belly');if(state.activities.includes('吃饭'))html+=`<p class="section-label">正餐吃什么<span>选一项</span></p>`+options(mealList,[state.meal],'meal')+(state.meal==='自定义'?`<label class="field">你想吃的<input id="customMeal" maxlength="50" value="${esc(state.customMeal)}" placeholder="比如：那家想吃很久的店"></label>`:'');if(state.activities.includes('咖啡 / 下午茶'))html+=`<p class="section-label">再来点什么<span>选一项</span></p>`+options(teaList,[state.tea],'tea')+(state.tea==='自定义'?`<label class="field">想喝或想吃的<input id="customTea" maxlength="50" value="${esc(state.customTea)}" placeholder="写下你想喝或想吃的"></label>`:'');html+=next('就吃这些 →');}
if(step===4){html=head('请指定见面坐标。',state.placeFree?'奶娃已接单，正在认真研究去哪里见你。':'本奶娃即将出动，目的地由你命名。',state.placeFree?'sad':'wave')+`<label class="field">想去哪里？<textarea id="place" maxlength="120" placeholder="写个地点、店名，或者大致区域。\n例如：学校旁边那家火锅店" ${state.placeFree?'disabled':''}>${esc(state.place)}</textarea></label>`+chips(['地点你来定'],state.placeFree?['地点你来定']:[],'placeFree')+`<div class="bubble">奶娃：路可以绕，见你这件事不能绕。</div>`+next('生成我们的约定 ♡');}
if(step===5){html=head('把这次见面，认真收藏。','嘴上说随便，和你见面要有凭有据。','doublePeace')+cardView();}
$('#app').innerHTML=html;bind();bindExperience();}
function toggleTimeChoice(value){const key=value==='日期你来定'?'dateFree':value==='睡到自然醒'?'sleepIn':'timeFree';state[key]=!state[key];if(state[key]&&key==='sleepIn')state.timeFree=false;if(state[key]&&key==='timeFree')state.sleepIn=false;}
function setField(k,v){state[k]=v;if(k==='date'&&typeof refreshWeather==='function')refreshWeather();}
function bind(){document.querySelectorAll('[data-back]').forEach(b=>b.onclick=back);for(const k of ['date','time','customActivity','customMeal','customTea','place']){const el=$('#'+k);if(el)el.oninput=()=>setField(k,el.value);}
document.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>{const g=b.dataset.group,v=b.dataset.value;if(g==='activities')lastActivity=v;if(g==='prefs'||g==='activities'){let list=state[g];if(list.includes(v))state[g]=list.filter(x=>x!==v);else state[g]=[...list,v];if(g==='activities'){if(v==='你来定'&&state.activities.includes(v))state.activities=['你来定'];else if(v!=='你来定')state.activities=state.activities.filter(x=>x!=='你来定');if(!state.activities.includes('吃饭')){state.meal='';state.customMeal='';}if(!state.activities.includes('咖啡 / 下午茶')){state.tea='';state.customTea='';}}}else if(g==='free'){toggleTimeChoice(v);}else if(g==='placeFree')state.placeFree=!state.placeFree;else state[g]=v;render();});
if($('#yes'))$('#yes').onclick=()=>go(1);if($('#no')){const b=$('#no');
// Move only after a completed tap, so the finger never lands on another control.
b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();dodge();});
b.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse'&&e.buttons===0)dodge();});}
if($('#next'))$('#next').onclick=()=>{const err=validate(step);if(err){$('#error').textContent=err;return;}go(step===2?(needsFood()?3:4):step+1);};
if($('#save'))$('#save').onclick=saveCard;if($('#copy'))$('#copy').onclick=copyText;if($('#restart'))$('#restart').onclick=()=>{state=initial();noCount=0;touchCount=0;lastActivity='';cardTheme='cinema';letterOpened=false;go(0);};}
const refusalReactions=[
 {mood:'bashful',text:'奶娃：哦……那我先低头委屈一小会儿。',button:'再想想嘛'},
 {mood:'pout',text:'奶娃：真的不来嘛？你再看看我这张脸。',button:'看我一眼嘛'},
 {mood:'rolling',text:'奶娃：我不听我不听！（开始原地打滚）',button:'真的不来？'},
 {mood:'lying',text:'奶娃：已躺下。需要一次约会才能起来。',button:'扶我一下嘛'},
 {mood:'belly',text:'奶娃：那我请你吃好吃的，这招总行了吧？',button:'再给次机会'},
 {mood:'plead',text:'奶娃：喵？为了这次约会，已经放下所有包袱。',button:'求你了嘛'}
];
function dodge(){const b=$('#no');if(!b)return;noCount++;const positions=[0,100,35,75];const x=positions[(noCount-1)%positions.length];const reaction=refusalReactions[(noCount-1)%refusalReactions.length];b.style.left=x+'%';b.style.setProperty('--dodge-x',-x+'%');b.textContent=reaction.button;const art=$('#heroMeme');art.outerHTML=moodArt(reaction.mood,'heroMeme');const current=$('#heroMeme');current.classList.add('reacting');current.onanimationend=()=>current.classList.remove('reacting');$('#plead').textContent=reaction.text;}
function validate(n){if(n===1){if(!state.dateFree&&!state.date)return '先选个日期，或把日期交给我来定。';if(!state.dateFree&&state.date<today())return '那天已经过去啦，选一个未来的见面日吧。';if(!state.timeFree&&!state.sleepIn&&!state.time)return '还差一个时间，也可以选“时间你来定”或“睡到自然醒”。';if(!state.dateFree&&!state.timeFree&&!state.sleepIn&&new Date(state.date+'T'+state.time)<=new Date())return '这个时间已经过去啦，稍微往后选一点。';}if(n===2){if(!state.activities.length)return '至少选一件想一起做的事吧。';if(state.activities.includes('自定义')&&!state.customActivity.trim())return '把你想一起做的事写下来吧。';}if(n===3){if(state.activities.includes('吃饭')&&(!state.meal||(state.meal==='自定义'&&!state.customMeal.trim())))return '选一个餐饮选项，或写下想吃什么。';if(state.activities.includes('咖啡 / 下午茶')&&(!state.tea||(state.tea==='自定义'&&!state.customTea.trim())))return '下午茶还没选好，也可以交给我来定。';}if(n===4&&!state.placeFree&&!state.place.trim())return '写一个想去的地方，或选“地点你来定”。';return '';}
function summary(){let date='你来定';if(!state.dateFree&&state.date){const d=new Date(state.date+'T12:00:00');date=`${d.getFullYear()}年${d.getMonth()+1}月${d.getDate()}日 · 周${'日一二三四五六'[d.getDay()]}`;}return {date,time:state.sleepIn?'睡到自然醒':state.timeFree?'你来定':state.time,activities:state.activities.map(a=>a==='自定义'?state.customActivity.trim():a).join(' + '),food:[...(state.activities.includes('吃饭')?[state.meal==='自定义'?state.customMeal.trim():state.meal]:[]),...(state.activities.includes('咖啡 / 下午茶')?[state.tea==='自定义'?state.customTea.trim():state.tea]:[])].join(' / '),place:state.placeFree?'你来定':state.place.trim(),preferences:[...state.prefs]};}
function plainText(){const d=summary();return `♡ ${invitation.to}和${invitation.from}的见面小约定\n日期：${d.date}\n时间：${d.time}\n一起做：${d.activities}${d.food?'\n吃点什么：'+d.food:''}\n地点：${d.place}${d.preferences.length?'\n小暗示：'+d.preferences.join('、'):''}\n\n我会装作不在意，然后提前到场。奶娃作证！\n—— ${invitation.sign}`;}
async function copyText(){try{await navigator.clipboard.writeText(plainText());showToast('约定已复制，去微信粘贴给我吧。');}catch{const el=document.createElement('textarea');el.value=plainText();document.body.append(el);el.select();const ok=document.execCommand('copy');el.remove();showToast(ok?'已复制约定文字':'复制未成功，可以保存图片发给我。');}}
for(const src of Object.values(images)){const preload=new Image();preload.src=src;}
$('#closeImage').onclick=()=>$('#imageDialog').close();
// Optional browser-native tools share the exact state used by the invitation UI.
const toolLifecycle=new AbortController();
if(document.modelContext?.registerTool){const defs=[{name:'read_date_invitation',title:'查看当前约会安排',description:'Read the current invitation selections without confirming or sharing them.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({step,selections:summary()})},{name:'start_new_date_invitation',title:'重新开始约会邀请',description:'Clear this round of choices and return to the invitation opening screen. Does not send anything.',inputSchema:{type:'object',properties:{confirmReset:{type:'boolean',const:true}},required:['confirmReset'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(!input||input.confirmReset!==true)throw Error('Explicit reset confirmation is required');state=initial();noCount=0;touchCount=0;lastActivity='';cardTheme='cinema';letterOpened=false;go(0);return {step:0,reset:true};}}];for(const t of defs){try{Promise.resolve(document.modelContext.registerTool(t,{signal:toolLifecycle.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>toolLifecycle.abort(),{once:true});}
